[project]
name = "test-case-automation"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "allure-pytest>=2.16.2",
    "pytest>=9.1.1",
    "pytest-playwright>=0.9.0",
    "pytest-xdist>=3.8.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "ruff>=0.16.9",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-n 4 --dist loadfile"